vim.pack.add({
  "https://github.com/tpope/vim-repeat",
  "https://github.com/jiangmiao/auto-pairs",
  "https://github.com/alvan/vim-closetag",
  "https://github.com/tomtom/tcomment_vim",
  "https://github.com/tommcdo/vim-lion",
  "https://github.com/tpope/vim-abolish",
  "https://github.com/scrooloose/nerdtree",
  "https://github.com/hrsh7th/nvim-cmp",
  "https://github.com/hrsh7th/cmp-path",
  "https://github.com/hrsh7th/cmp-buffer",
  "https://github.com/hrsh7th/cmp-nvim-lsp",
  "https://github.com/hrsh7th/cmp-nvim-lsp-signature-help",
  "https://github.com/hrsh7th/cmp-vsnip",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/echasnovski/mini.notify",
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/nvimtools/none-ls.nvim",
  "https://github.com/liuchengxu/vista.vim",
  "https://github.com/hrsh7th/vim-vsnip",
  "https://github.com/hrsh7th/vim-vsnip-integ",
  "https://github.com/rafamadriz/friendly-snippets",
  "https://github.com/mbbill/undotree",
  "https://github.com/nvim-treesitter/nvim-treesitter",
  "https://github.com/sheerun/vim-polyglot",
  "https://github.com/jasdel/vim-smithy",
  "https://github.com/dag/vim-fish",
  "https://github.com/guns/vim-clojure-static",
  "https://github.com/guns/vim-sexp",
  "https://github.com/tpope/vim-sexp-mappings-for-regular-people",
  "https://github.com/ibhagwan/fzf-lua",
  "https://github.com/tpope/vim-fugitive",
  "https://github.com/tpope/vim-rhubarb",
  "https://github.com/machakann/vim-sandwich",
  "https://github.com/lukas-reineke/indent-blankline.nvim",
  "https://codeberg.org/andyg/leap.nvim",
  "https://github.com/justinmk/vim-ipmotion",
  "https://github.com/rktjmp/lush.nvim",
  "https://github.com/ab-dx/ares.nvim",
  "https://github.com/savq/melange-nvim",
  "https://github.com/ramojus/mellifluous.nvim",
  "https://github.com/rebelot/kanagawa.nvim",
  "https://github.com/sainnhe/everforest",
  "https://github.com/zenbones-theme/zenbones.nvim",
  "https://github.com/rose-pine/neovim",
  "https://github.com/fcpg/vim-fahrenheit",
  "https://github.com/AlessandroYorba/alduin",
  "https://github.com/fcpg/vim-orbital",
  "https://github.com/fcpg/vim-farout",
  "https://github.com/habamax/vim-gruvbit",
})

vim.g.lion_squeeze_spaces = 1

vim.g.NERDTreeMinimalUI = 1
vim.g.NERDTreeDirArrows = 1
vim.g.NERDTreeQuitOnOpen = 1
vim.g.clojure_align_multiline_strings = 1
vim.g.sexp_insert_after_wrap = "false"
vim.g.ip_skipfold = 1
