#!/usr/bin/env sh
#
# chunkc core::log_file stdout
#
# chunkc core::log_level warn
#
# chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
#
# chunkc core::hotload 0
#
# chunkc set custom_bar_enabled            0
# chunkc set custom_bar_all_monitors       0
# chunkc set custom_bar_offset_top         0
# chunkc set custom_bar_offset_bottom      0
# chunkc set custom_bar_offset_left        0
# chunkc set custom_bar_offset_right       0
#
# chunkc set global_desktop_mode           bsp
# chunkc set global_desktop_offset_top     40
# chunkc set global_desktop_offset_bottom  40
# chunkc set global_desktop_offset_left    40
# chunkc set global_desktop_offset_right   40
# chunkc set global_desktop_offset_gap     15
#
# chunkc set desktop_padding_step_size     10.0
# chunkc set desktop_gap_step_size         5.0
#
# chunkc set bsp_spawn_left                1
# chunkc set bsp_optimal_ratio             1.618
# chunkc set bsp_split_mode                optimal
# chunkc set bsp_split_ratio               0.5
#
# chunkc set monitor_focus_cycle           1
# chunkc set window_focus_cycle            monitor
#
# chunkc set mouse_follows_focus           intrinsic
# chunkc set window_float_next             0
# chunkc set window_region_locked          1
#
# chunkc set mouse_move_window             "fn 1"
# chunkc set mouse_resize_window           "fn 2"
# chunkc set mouse_motion_interval         35
#
# chunkc set preselect_border_color        0xffd75f5f
# chunkc set preselect_border_width        5
# chunkc set preselect_border_radius       0
# chunkc set preselect_border_outline      0
#
# chunkc set window_float_topmost          0
# chunkc set window_fade_inactive          0
# chunkc set window_fade_alpha             0.85
# chunkc set window_fade_duration          0.25
# chunkc set window_use_cgs_move           0
#
# chunkc set focused_border_color          0xffffffff
# chunkc set focused_border_width          5
# chunkc set focused_border_radius         5
# chunkc set focused_border_outline        1
# chunkc set focused_border_skip_floating  0
# chunkc set focused_border_skip_monocle   0
#
# chunkc set ffm_bypass_modifier           fn
# chunkc set ffm_standby_on_float          1


# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

echo "yabai configuration loaded.."

